### ISSUE TITLE
Availability to fork and use 

### ISSUE THREAD

**Issue by sirgalleto** [colombia-dev/pataconf#22]
Hi there 👋 

I'm Sebastián a.k.a. [sirgalleto](www.twitter.com/sirgalleto), a Colombian living in Mexico. First of all, I wanna congratulate you for the awesome effort put in this page, looks really awesome and perfect. 

Actually, I'm co-organizing a similar event here in Guadalajara Mexico, is our second version and for this year I'd like to use this repo as the base for our page [posadev.mx](posadev.mx) which is a mess. So, I want to ask you for the availability to fork this repo. I know that is a public and MIT repo, but I prefer to notify you first and keep open relations for future events. 

Thank you!

**Comment by khriztianmoreno** [comment]
Hi @sirgalleto, Of course, you can make the fork of this repo, we are proud to know that in addition to being useful for our event, it will be useful for other people.

Feel free to fork, greetings.

**Comment by sirgalleto** [comment]
Excellent, thank you and let's keep in contact!

**Comment by heryxpc** [comment]
Hi @khriztianmoreno quick notification, I will be the one doing the fork for posadev.mx.
Thanks for the help!
